### ISSUE TITLE
Using old i2cssh config files

### ISSUE THREAD

**Issue by kurktchiev** [peh/node-i2cssh#1]
Hey so I just stumbled on your re-write and I like it, much simpler and faster than original, but it seems to not be able to use my already existing .i2cssh file :(, my node knowledge is non existent otherwise I would start doing some PRs. Any chance to add that?

**Comment by peh** [comment]
Yes it is on the Todo list! I am currently polishing the ec2 intergration .

**Comment by peh** [comment]
so i did some first integrations, clusters should already work. can you check if it's working with your existing file. and do you have any preference on what should work next

**Comment by kurktchiev** [comment]
Just tested and it did not like my config file. GUessing its not ignoring the direction and boradcast bits. 

``` yaml
---
version: 2
clusters:
  direction: row
  broadcast: true
  sakai-dev:
    columns: 3
    hosts:
      - lmapp0d
      - lmapp1d
      - lmadmind
  appbuild:
    hosts:
      - appbuild0
      - appbuild1
```

doing `i2cssh -C .i2csshrc -c appbuild` just returns and does nothing.
